apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense-tracker
spec:
  type: ClusterIP
  selector:
    app: expense-backend
  ports:
    - port: 5000
      targetPort: 5000