apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secrets
  namespace: expense-tracker
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://saradobrevska_db_user:kCmAvSXryFHnS81q@cluster0.iospzrl.mongodb.net/expense_tracker?appName=Cluster0"